services:
  - type: web
    name: house-mark-tech
    env: java
    plan: free
    branch: main
    buildCommand: "./mvnw clean install"
    startCommand: "java -jar target/*.jar"
    envVars:
      - key: JAVA_VERSION
        value: 17
