services:
  - type: web
    name: house-mark-tech-api
    plan: free
    branch: main
    buildCommand: ./mvnw clean install
    startCommand: java -jar target/House_Mark_Tech-0.0.1-SNAPSHOT.jar
    envVars:
      - key: JAVA_VERSION
        value: 17
